const data_raw = {
  0: [
    "AccordionActions",
    "AccordionDetails",
    "Avatar",
    "Badge",
    "BottomNavigation",
    "Box",
    "ButtonBase/Ripple",
    "ButtonGroup",
    "CardActions",
    "CardContent",
    "CardMedia",
    "CircularProgress",
    "ClickAwayListener",
    "Collapse",
    "Container",
    "DialogActions",
    "DialogContent",
    "Divider",
    "Fade",
    "FormControl",
    "FormControl/formControlState",
    "FormGroup",
    "GlobalStyles",
    "Grid",
    "Grow",
    "Hidden/HiddenCss",
    "Hidden/withWidth",
    "Icon",
    "ImageList",
    "ImageListItem",
    "ImageListItemBar",
    "LinearProgress",
    "List",
    "ListItemAvatar",
    "ListItemIcon",
    "ListItemSecondaryAction",
    "ListSubheader",
    "NativeSelect/NativeSelectInput",
    "NoSsr",
    "OutlinedInput/NotchedOutline",
    "Paper",
    "Portal",
    "Radio/RadioButtonIcon",
    "Rating",
    "Skeleton",
    "Slide",
    "Slider",
    "SpeedDialIcon",
    "Stack",
    "Step",
    "StepConnector",
    "StyledEngineProvider",
    "SvgIcon",
    "Table",
    "TableBody",
    "TableCell",
    "TableContainer",
    "TableFooter",
    "TableHead",
    "TableRow",
    "Tabs/ScrollbarSize",
    "TextareaAutosize",
    "ToggleButtonGroup/isValueSelected",
    "Toolbar",
    "Typography",
    "Unstable_TrapFocus",
    "Zoom",
    "darkScrollbar",
    "internal/animate",
    "locale",
    "transitions/transition",
  ],
  1: {
    Accordion: ["Collapse", "Paper"],
    AlertTitle: ["Typography"],
    AppBar: ["Paper"],
    AvatarGroup: ["Avatar"],
    Backdrop: ["Fade"],
    "ButtonBase/TouchRipple": ["ButtonBase/Ripple"],
    Card: ["Paper"],
    CardHeader: ["Typography"],
    CssBaseline: ["GlobalStyles"],
    DialogContentText: ["Typography"],
    DialogTitle: ["Typography"],
    FormControlLabel: ["FormControl", "Typography"],
    FormHelperText: ["FormControl/formControlState"],
    FormLabel: ["FormControl/formControlState"],
    "Hidden/HiddenJs": ["Hidden/withWidth"],
    InputAdornment: ["Typography"],
    InputBase: [
      "FormControl/formControlState",
      "GlobalStyles",
      "TextareaAutosize",
    ],
    Link: ["Typography"],
    ListItemText: ["Typography"],
    MenuList: ["List"],
    MobileStepper: ["LinearProgress", "Paper"],
    Popper: ["Portal"],
    RadioGroup: ["FormGroup"],
    SnackbarContent: ["Paper"],
    StepContent: ["Collapse"],
    StepIcon: ["SvgIcon"],
    Stepper: ["StepConnector"],
    ToggleButtonGroup: ["ToggleButtonGroup/isValueSelected"],
    transitions: ["transitions/transition"],
  },
  2: {
    ButtonBase: ["ButtonBase/TouchRipple"],
    FilledInput: ["InputBase", "InputBase"],
    Hidden: ["Hidden/HiddenCss", "Hidden/HiddenJs"],
    Input: ["InputBase", "InputBase"],
    InputLabel: ["FormControl/formControlState", "FormLabel"],
    Modal: ["Backdrop"],
    OutlinedInput: ["InputBase", "OutlinedInput/NotchedOutline"],
    ScopedCssBaseline: ["CssBaseline"],
    Snackbar: ["Grow", "SnackbarContent"],
    StepLabel: ["StepIcon"],
    Tooltip: ["Grow", "Popper"],
  },
  3: {
    AccordionSummary: ["ButtonBase"],
    BottomNavigationAction: ["ButtonBase"],
    "Breadcrumbs/BreadcrumbCollapsed": ["ButtonBase"],
    Button: ["ButtonBase"],
    CardActionArea: ["ButtonBase"],
    Chip: ["ButtonBase"],
    Dialog: ["Backdrop", "Fade", "Modal", "Paper"],
    Drawer: ["Modal", "Paper", "Slide"],
    Fab: ["ButtonBase"],
    IconButton: ["ButtonBase"],
    ListItemButton: ["ButtonBase"],
    MenuItem: ["ButtonBase", "Divider", "ListItemIcon", "ListItemText"],
    NativeSelect: [
      "FormControl/formControlState",
      "Input",
      "NativeSelect/NativeSelectInput",
    ],
    PaginationItem: ["ButtonBase"],
    Popover: ["Grow", "Modal", "Paper"],
    StepButton: ["ButtonBase", "StepLabel"],
    Tab: ["ButtonBase"],
    TabScrollButton: ["ButtonBase"],
    TableSortLabel: ["ButtonBase"],
    ToggleButton: ["ButtonBase"],
    "internal/SwitchBase": ["ButtonBase"],
  },
  4: {
    Alert: ["IconButton", "Paper"],
    Autocomplete: ["Chip", "IconButton", "ListSubheader", "Paper", "Popper"],
    Breadcrumbs: ["Breadcrumbs/BreadcrumbCollapsed", "Typography"],
    Checkbox: ["internal/SwitchBase"],
    ListItem: ["ButtonBase", "ListItemButton", "ListItemSecondaryAction"],
    Menu: ["MenuList", "Paper", "Popover"],
    Pagination: ["PaginationItem"],
    Radio: ["Radio/RadioButtonIcon", "internal/SwitchBase"],
    SpeedDial: ["Fab", "Zoom"],
    SpeedDialAction: ["Fab", "Tooltip"],
    "SwipeableDrawer/SwipeArea": ["Drawer"],
    Switch: ["internal/SwitchBase"],
    "TablePagination/TablePaginationActions": ["IconButton"],
    Tabs: ["TabScrollButton", "Tabs/ScrollbarSize", "internal/animate"],
  },
  5: {
    "Select/SelectInput": ["Menu", "NativeSelect/NativeSelectInput"],
    SwipeableDrawer: ["Drawer", "SwipeableDrawer/SwipeArea"],
  },
  6: {
    Select: [
      "FilledInput",
      "FormControl/formControlState",
      "Input",
      "NativeSelect/NativeSelectInput",
      "OutlinedInput",
      "Select/SelectInput",
    ],
  },
  7: {
    TablePagination: [
      "InputBase",
      "MenuItem",
      "Select",
      "TableCell",
      "TablePagination/TablePaginationActions",
      "Toolbar",
    ],
    TextField: [
      "FilledInput",
      "FormControl",
      "FormHelperText",
      "Input",
      "InputLabel",
      "OutlinedInput",
      "Select",
    ],
  },
}

const data = [data_raw].map(({ 0: top, ...rest }) => {
  const keys = [...top, ...Object.values(rest).flatMap(x => Object.keys(x))]
    .flat()
    .sort()

  const flattened = Object.fromEntries(
    top
      .map(key => [key, []])
      .concat(...Object.values(rest).map(x => Object.entries(x)))
  )

  const deps = Object.values(flattened).flat().sort()

  const numOfDependantsCountByKey = Object.fromEntries(
    keys.map(key => [key, deps.filter(dep => dep === key).length + 1])
  )

  const x = keys.map(key => ({
    name: key,
    size: numOfDependantsCountByKey[key],
    imports: flattened[key],
  }))

  return x
}).flat()
